 --**********************************************************************************************************
--** NOMBRE SCRIPT        : TADM0281
--** OBJETIVO             : tabla que permite el insertar en la auditoria en caso 
--** ESQUEMA              : adm
--** NOMBRE               : AUDITORIA_LOG_APP
--** AUTOR                : DEIBY SIERRA
--** FECHA MODIFICACION   : 16/03/2023
--**********************************************************************************************************
CREATE TABLE "ADM"."AUDITORIA_LOG_APP" 
   (	"ALP_ID" NUMBER, 
	"ALP_LOG" VARCHAR2(4000 BYTE), 
	"ALP_TYPE_ERROR" VARCHAR2(20 BYTE), 
	"ALP_APLICATIVO" VARCHAR2(2000 BYTE), 
	"ALP_TRANSACCION" NUMBER(25,0), 
	"AUD_FECHA" DATE, 
	"AUD_USUARIO" VARCHAR2(30 BYTE), 
	"ALP_ESTADOTRANSACCION" VARCHAR2(40 BYTE)
   ) 
  SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER_DATA_OLD" ;
  /
   GRANT FLASHBACK ON "ADM"."AUDITORIA_LOG_APP" TO PUBLIC;
  GRANT DEBUG ON "ADM"."AUDITORIA_LOG_APP" TO PUBLIC;
  GRANT QUERY REWRITE ON "ADM"."AUDITORIA_LOG_APP" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "ADM"."AUDITORIA_LOG_APP" TO PUBLIC;
  GRANT REFERENCES ON "ADM"."AUDITORIA_LOG_APP" TO PUBLIC;
  GRANT UPDATE ON "ADM"."AUDITORIA_LOG_APP" TO PUBLIC;
  GRANT SELECT ON "ADM"."AUDITORIA_LOG_APP" TO PUBLIC;
  GRANT INSERT ON "ADM"."AUDITORIA_LOG_APP" TO PUBLIC;
  GRANT INDEX ON "ADM"."AUDITORIA_LOG_APP" TO PUBLIC;
  GRANT DELETE ON "ADM"."AUDITORIA_LOG_APP" TO PUBLIC;
  GRANT ALTER ON "ADM"."AUDITORIA_LOG_APP" TO PUBLIC;
  /
  CREATE UNIQUE INDEX "ADM"."PK_AUDITORIA_LOG_APP" ON "ADM"."AUDITORIA_LOG_APP" ("ALP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER_DATA_OLD" ;
  /
    CREATE SEQUENCE adm.SEQ_AUDITORIA_LOG_APP  start with 1 increment by 1
  maxvalue 99999
  minvalue 1
  NOCACHE ;
  /
  
  CREATE OR REPLACE TRIGGER "ADM"."DB_AUDITORIA_LOG_APP" 
Before
  INSERT ON ADM.AUDITORIA_LOG_APP REFERENCING NEW AS NEW
  FOR EACH ROW

  Begin
	Select ADM.SEQ_AUDITORIA_LOG_APP.Nextval
      INTO :NEW.ALP_ID
      FROM dual;	
  --
EXCEPTION
  WHEN OTHERS THEN
    raise_application_error(-20001, 'Error secuencia ADM.DB_AUDITORIA_LOG_APP:'||sqlerrm);
End;
/
ALTER TRIGGER "ADM"."DB_AUDITORIA_LOG_APP" ENABLE;
/
  ALTER TABLE "ADM"."AUDITORIA_LOG_APP" ADD CONSTRAINT "CK_ALP_TYPE_ERROR" CHECK (ALP_TYPE_ERROR IN ('WARNING','ERROR','INFO')) ENABLE;
  ALTER TABLE "ADM"."AUDITORIA_LOG_APP" ADD CONSTRAINT "PK_AUDITORIA_LOG_APP" PRIMARY KEY ("ALP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER_DATA_OLD"  ENABLE;
  ALTER TABLE "ADM"."AUDITORIA_LOG_APP" MODIFY ("ALP_TRANSACCION" NOT NULL ENABLE);
  ALTER TABLE "ADM"."AUDITORIA_LOG_APP" MODIFY ("ALP_TYPE_ERROR" NOT NULL ENABLE);
  ALTER TABLE "ADM"."AUDITORIA_LOG_APP" MODIFY ("ALP_ID" NOT NULL ENABLE);