--**********************************************************************************************************
--** NOMBRE SCRIPT        : TADM0278
--** OBJETIVO             : tabla que permite el seguimiento del analista en el aplicativos de mesa de contratos
--** ESQUEMA              : adm
--** NOMBRE               : seg_firma_estado 
--** AUTOR                : DEIBY SIERRA
--** FECHA MODIFICACION   : 16/03/2023
--**********************************************************************************************************

 CREATE TABLE "ADM"."SEG_MESA_CONTRATOS" 
   (	"SMC_ID" NUMBER, 
	"SMC_RESPONSABLE" VARCHAR2(30 BYTE), 
	"SMC_ESTADO_RESPONSABLE" VARCHAR2(30 BYTE), 
	"LIB_CONSECUTIVO" NUMBER(12,0), 
	"AUD_FECHA" DATE, 
	"AUD_USUARIO" VARCHAR2(30 BYTE), 
	"EST_FINAL" VARCHAR2(1000 BYTE), 
	"FECHA_FINAL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER_DATA_OLD" ;
  
  /
  GRANT FLASHBACK ON "ADM"."SEG_MESA_CONTRATOS" TO PUBLIC;
  GRANT DEBUG ON "ADM"."SEG_MESA_CONTRATOS" TO PUBLIC;
  GRANT QUERY REWRITE ON "ADM"."SEG_MESA_CONTRATOS" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "ADM"."SEG_MESA_CONTRATOS" TO PUBLIC;
  GRANT REFERENCES ON "ADM"."SEG_MESA_CONTRATOS" TO PUBLIC;
  GRANT UPDATE ON "ADM"."SEG_MESA_CONTRATOS" TO PUBLIC;
  GRANT SELECT ON "ADM"."SEG_MESA_CONTRATOS" TO PUBLIC;
  GRANT INSERT ON "ADM"."SEG_MESA_CONTRATOS" TO PUBLIC;
  GRANT INDEX ON "ADM"."SEG_MESA_CONTRATOS" TO PUBLIC;
  GRANT DELETE ON "ADM"."SEG_MESA_CONTRATOS" TO PUBLIC;
  GRANT ALTER ON "ADM"."SEG_MESA_CONTRATOS" TO PUBLIC;
  /
  
  CREATE UNIQUE INDEX "ADM"."PK_SEG_MESA_CONTRATOS" ON "ADM"."SEG_MESA_CONTRATOS" ("SMC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER_DATA_OLD" ;
  /
  CREATE SEQUENCE adm.seq_SEG_MESA_CONTRATOS  start with 1 increment by 1
  maxvalue 99999
  minvalue 1
  NOCACHE ;
  /
  CREATE OR REPLACE TRIGGER "ADM"."DB_SEG_MESA_CONTRATOS" 
Before
  INSERT ON ADM.SEG_MESA_CONTRATOS REFERENCING NEW AS NEW
  FOR EACH ROW

  Begin
	Select seq_SEG_MESA_CONTRATOS.Nextval
      INTO :NEW.SMC_ID
      FROM dual;	
  --
EXCEPTION
  WHEN OTHERS THEN
    raise_application_error(-20001, 'Error secuencia DB_SEG_MESA_CONTRATOS:'||sqlerrm);
End;

/
ALTER TRIGGER "ADM"."DB_SEG_MESA_CONTRATOS" ENABLE;
/
 ALTER TABLE "ADM"."SEG_MESA_CONTRATOS" ADD CONSTRAINT "PK_SEG_MESA_CONTRATOS" PRIMARY KEY ("SMC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER_DATA_OLD"  ENABLE;
  ALTER TABLE "ADM"."SEG_MESA_CONTRATOS" MODIFY ("LIB_CONSECUTIVO" NOT NULL ENABLE);
  ALTER TABLE "ADM"."SEG_MESA_CONTRATOS" MODIFY ("SMC_ESTADO_RESPONSABLE" NOT NULL ENABLE);
  ALTER TABLE "ADM"."SEG_MESA_CONTRATOS" MODIFY ("SMC_RESPONSABLE" NOT NULL ENABLE);
  ALTER TABLE "ADM"."SEG_MESA_CONTRATOS" MODIFY ("SMC_ID" NOT NULL ENABLE);
  
  